blog/urls.py
#! -*- encoding:utf-8 -*-
from django.conf.urls import patterns, url
from . import views

urlpatterns = [
    url(r'^$', views.post_list),
    url(r'^about_me', views.about_me, name='about_me'),
    url(r'^post_markdown', views.post_markdown, name='post_markdown'),
    url(r'^posts/search/$', views.full_search, name='full_search'),
    url(r'^posts/upload/$', views.upload, name='upload'),
    url(r'^posts/add_category/$', views.add_category, name='upload'),
    url(r'^posts/category/(?P<cg>\w+)$', views.post_list_by_category, name='list_by_cg'),
    url(r'^site_media/(?P<path>.*)', 'django.views.static.serve', {'document_root': 'static/upload/images/'}),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>[0-9]+)/edit_tinymce/$', views.post_edit, name='post_edit_tinymce'),
    url(r'^post/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
    url(r'^post/(?P<pk>[0-9]+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>[0-9]+)/remove/$', views.post_remove, name='post_remove'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'^accounts_wb/login/$', views.login),
    url(r'^accounts_wb/logout/$', views.logout, {'next_page': '/'}),
    url(r'^search/', include('haystack.urls')),
]

blog/models.py
#! -*- encoding:utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.utils import timezone
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Post(models.Model):
    class Meta:
        app_label = 'blog'
        verbose_name = u'文章'
        verbose_name_plural = u'文章'
    author = models.ForeignKey(User)
    title = models.CharField(max_length=200)
    text = models.TextField()
    #markdown_text = models.TextField()
    #markdown_pretext = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    category = models.ForeignKey(Category)
    is_markdown = models.BooleanField(default=True)
    markdown_text = models.TextField(default='default_text')
    tinymce_text = models.TextField(default='default_text')

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

blog/forms.py
#! -*- encoding:utf-8 -*-
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('category', 'is_markdown', 'title', 'text', 'markdown_text', 'tinymce_text')
        labels = {
            'category': '分类目录',
            'is_markdown': '是否保存为markdown文本',
            'title': '标题',
            'text': 'markdown文本',
            'markdown_text': 'markdown预览',
            'tinymce_text': 'tinymce文本',
        }

blog/views.py
# encoding=utf8
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from .models import Post, Category
from .forms import PostForm
from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from haystack.forms import SearchForm
from django.http import HttpResponse, HttpResponseRedirect
from PIL import Image
#python3.4 强制encoding utf8，所以不需要下面两句
#import sys
#reload(sys)
#sys.setdefaultencoding( "utf-8" )

def full_search(request):
    """全局搜索"""
    keywords = request.GET['q']
    sform = SearchForm(request.GET)
    posts = sform.search()
    return render(request, 'blog/post_search_list.html',
                  {'posts': posts, 'list_header': '关键字 \'{}\' 搜索结果'.format(keywords)})

@login_required
def add_category(request):
    cate_name = request.GET.get('category_name')
    url_name = request.GET.get('current_url')
    category = Category.objects.create(name=cate_name)
    return HttpResponseRedirect(url_name)

# Create your views here.

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    #post.text = post.text.replace('[!--more--]', '', 1)
    return render(request, 'blog/post_detail.html', {'post': post})

def post_list(request):
    """所有已发布文章"""
    postsAll = Post.objects.annotate(num_comment=Count('id')).filter(
        published_date__isnull=False).prefetch_related('category').order_by('-published_date')
    paginator = Paginator(postsAll, 5)  # Show 5 contacts per page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post_list.html', {'posts': posts, 'page': True})

def post_list_by_category(request, cg):
    """根据目录列表已发布文章"""
    posts = Post.objects.filter(
        published_date__isnull=False, category__id=cg).prefetch_related(
        'category').order_by('-published_date')
    category = Category.objects.filter(id=cg)
    return render(request, 'blog/post_list.html',
                  {'posts': posts, 'list_header': '\'{}\' 分类的存档'.format(category[0].name)})

@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog.views.post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    old_flag = post.is_markdown
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            new_flag = post.is_markdown
            if old_flag == new_flag:
                return redirect('blog.views.post_detail', pk=post.pk)
            else:
                if post.is_markdown:
                    return render(request, 'blog/post_edit.html', {'form': form})
                else:
                    return render(request, 'blog/post_edit_tinymce.html', {'form': form})
    else:
        form = PostForm(instance=post)
    if post.is_markdown:
        return render(request, 'blog/post_edit.html', {'form': form})
    else:
        return render(request, 'blog/post_edit_tinymce.html', {'form': form})

@login_required
def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('-created_date')
    return render(request, 'blog/post_draft_list.html', {'posts': posts})

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog.views.post_detail', pk=pk)

@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blog.views.post_list')

@login_required
def upload(request):
    try:
        file = request.FILES['image']
        #form提交的文件的名字，上面html里面的name
        img = Image.open(file)
        img.thumbnail((500, 500), Image.ANTIALIAS)
        img.save('static/upload/images/'+file.name, img.format)
        #图片的name和format都是动态获取的，支持png，jpeg，gif等
    except Exception as e:
        return HttpResponse('error %s' % e)
    path = '/site_media/'+file.name
    return HttpResponse("<script>top.$('.mce-btn.mce-open').parent().find('.mce-textbox').val('%s').closest('.mce-window').find('.mce-primary').click();</script>" % path)

def about_me(request):
    return render(request, 'blog/about_me.html', {})

def post_markdown(request):
    return render(request, 'blog/post_markdown.html', {})

blog/templates/blog/about_me.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block content %}
<div class="container">
    <!-- div class="col-md-4"><img src="{% static 'images/wb.jpg' %}" class="img-rounded" alt="Cinque Terre" width="300" height="280">
    </div -->
    <div class="col-md-8">
        <ul class="list-group">
            <li class="list-group-item" style="background-color:#66cc99">2015从BUAA毕业，当前北漂于一家外企</li>
            <li class="list-group-item" style="background-color:#66cc99">Tags: angularjs bootstrap restful python( flask ) celery rabbitmq apache vim linux, go nginx c/c++ ruby( rails ) redis java, fullstack</li>
            <li class="list-group-item" style="background-color:#66cc99">正在做的事情关于openstack docker kubernetes devops</li>
            <li class="list-group-item" style="background-color:#66cc99">博客源码大家可以共享,主要是tinymce和markdown:<a href="https://github.com/juandx/myblog" target="_blank">https://github.com/juandx/myblog</a></li>
            <li class="list-group-item" style="background-color:#66cc99">以前使用的cnblogs:<a href="http://www.cnblogs.com/juandx/" target="_blank">http://www.cnblogs.com/juandx/</a></li>
            <li class="list-group-item" style="background-color:#66cc99">欢迎大家交流 Email:juandx@163.com</li>
        </ul>
    </div>
</div>
{% endblock content %}

blog/templates/blog/base.html
{% load staticfiles %}
{% load i18n %}
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'highlightjs/styles/obsidian.css' %}"/>
    <link type="text/css" rel="stylesheet" href="{% static 'syntaxhighlighter/styles/shCoreRDark.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'highlightjs/highlight.pack.js' %}"></script>
    <script type="text/javascript" src="{% static 'syntaxhighlighter/scripts/shCore.js' %}"></script>
    <script type="text/javascript">SyntaxHighlighter.config.bloggerMode = true;SyntaxHighlighter.all();</script>
    <script type="text/javascript">hljs.initHighlightingOnLoad();</script>
    <title>{% trans 'WenBin Blog'%}</title>
    <!-- title>陈严的博客</title -->
</head>
<body class="body_bgc">
    <div class="container">
        <div class="row">
            <div class="col-md-11">
                <div class="page-header">
                    <h1><a class="about_me" href="{% url 'blog.views.about_me' %}">about me</a></h1>
                    {% if user.is_authenticated %}
                    <a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
                    <a href="{% url 'post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
                    <p class="top-menu">Hello {{ user.username }}<small>&nbsp;<a href="{% url 'django.contrib.auth.views.logout' %}">Log out</a></p>
                    {% else %}
                    <!-- a href="{% url 'django.contrib.auth.views.login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a -->
                    {% endif %}
                    <h1><a href="{% url 'blog.views.post_list' %}">Bin's Blog</a></h1>
                    <!-- h1><a href="{% url 'blog.views.post_list' %}">陈严的博客</a></h1 -->
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-9">
                {% block content %}
                {% endblock %}
            </div>
            <div class="col-md-2">
                <!-- searchbox START -->
                <div id="searchbox">
                    <form action="{% url 'blog.views.full_search' %}" method="get">
                        <div>
                            <label>
                                <input type="text" class="textfield searchtip" name="q" size="12" value="search" onFocus="if(value==defaultValue){value='';this.style.color='#000'}" onBlur="if(!value){value=defaultValue; this.style.color='#999'}" style="color:#999;text-align:left;" ng-model="owner_name" id="owner" />
                            </label>
                        </div>
                    </form>
                </div>
                <!-- searchbox END -->
                <h5><a href="{% url 'post_markdown' %}" target="_blank">online markdown</a></h5>
                <div id="sidebar">
                    <!-- sidebar north START -->
                    <div id="northsidebar" class="sidebar">
                        <div id="categories-2" class="widget widget_categories">
                            <h3 class="post_category">CATEGORIES</h3>
                            <ul>
                                {% for ca in CATEGORIES %}
                                    <li class="cat-item cat-item-10">
                                        <a href="{% url 'blog.views.post_list_by_category' cg=ca.id %}"
                                            title="{{ ca.name }}">{{ ca.name }}({{ca.num_post}})</a>
                                    </li>
                                {% endfor %}
                            </ul>
                            {% if user.is_authenticated %}
                            <div class="widget">
                                <button class="cat-item cat-item-10 btn btn-primary" data-toggle="modal" data-target="#AddModal">添加分类</button>
                                <!-- 模态框（Modal） -->
                                <div class="modal fade" id="AddModal" tabindex="-1" role="dialog" 
                                    aria-labelledby="myModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                       <div class="modal-content">
                                          <div class="modal-header">
                                             <button type="button" class="close" 
                                                data-dismiss="modal" aria-hidden="true">
                                                   &times;
                                             </button>
                                             <h4 class="modal-title" id="myModalLabel">
                                                输入新添加的分类
                                             </h4>
                                          </div>
                                          <form action="{% url 'blog.views.add_category' %}" class="crawl" method="GET">
                                              <div class="modal-body">
                                                  <div class="row">
                                                      <h4 class="label-warning">提交前请先保存文章</h4>
                                                  </div>
                                                  <div class="row">
                                                      <input name="category_name" class="form-control" value="{{ cate_name|escape }}"></input>
                                                      <input type="hidden" name="current_url" class="form-control" value="{{request.get_full_path|escape }}"></input>
                                                  </div>
                                              </div>
                                              <div class="modal-footer">
                                                 <button type="button" class="btn btn-default" 
                                                    data-dismiss="modal">关闭
                                                 </button>
                                                 <button type="submit" class="btn btn-primary" >
                                                    提交
                                                 </button>
                                              </div>
                                          </form>
                                       </div><!-- /.modal-content -->
                                    </div>
                                </div><!-- /.modal -->
                            </div>
                        </div>
                        {% endif %}
                    </div>
                    <!-- sidebar north END -->
                </div>
            </div>
        </div>
    </div>


    <script class="javascript" src="{% static 'syntaxhighlighter/scripts/shBrushJScript.js' %}"></script>
    <script class="javascript" src="{% static 'syntaxhighlighter/scripts/shBrushBash.js' %}"></script>
    <script class="javascript" src="{% static 'syntaxhighlighter/scripts/shBrushPhp.js' %}"></script>
    <script class="javascript" src="{% static 'syntaxhighlighter/scripts/shBrushJava.js' %}"></script>
    <script class="javascript" src="{% static 'syntaxhighlighter/scripts/shBrushSql.js' %}"></script>
    <script class="javascript" src="{% static 'syntaxhighlighter/scripts/shBrushXml.js' %}"></script>
    <script class="javascript" src="{% static 'syntaxhighlighter/scripts/shBrushPython.js' %}"></script>
    <script class="javascript" src="{% static 'syntaxhighlighter/scripts/shBrushCss.js' %}"></script>
    <script class="javascript" src="{% static 'syntaxhighlighter/scripts/shBrushCpp.js' %}"></script>
</body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block content %}
    <div class="post-meta">
        {% if post.published_date %}
            <span class="post_date">
                {{ post.published_date }}
            </span>
        {% else %}
            {% if user.is_authenticated %}
                <a class="btn btn-default" href="{% url 'blog.views.post_publish' pk=post.pk %}">Publish</a>
            {% endif %}
        {% endif %}
        {% if user.is_authenticated %}
            <a class="btn btn-default" href="{% url 'post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
            <a class="btn btn-default" href="{% url 'post_remove' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
        {% endif %}
        <div class="under">
            <span class="categories post_date">category: </span>
            <span>
                <a href="{% url 'blog.views.post_list_by_category' cg=post.category.id %}"
                   rel="category">{{ post.category.name }}
                </a>
            </span>
        </div>
    </div>
    <div class="post">
        <h1><a href="{% url 'blog.views.post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
    </div>
    </br>
    <div>
        <h4>转载请注明出处:&nbsp<a href="{% url 'blog.views.post_detail' pk=post.pk %}" target="_blank">转载自Bin's Blog:&nbsp; <b>{{ post.title }}(&nbsp;http://www.wenbin.cf{% url 'blog.views.post_detail' pk=post.pk %}&nbsp;)</b></a></h4>
    </div>
    </br>
    <div class="post_detail">
        <p>
            {% autoescape off %}
                {% if post.is_markdown %}
                        {{ post.markdown_text }}
                {% else %}
                    {{ post.tinymce_text }}
                {% endif %}
            {% endautoescape %}
        </p>
    </div>
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}
{% block content %}
    {% for post in posts %}
        <div class="post">
            <p class="date">created: {{ post.created_date|date:'d-m-Y' }}</p>
            <h1><a href="{% url 'blog.views.post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p></p>
            <p>
                {% autoescape off %}
                {% if post.is_markdown %}
                    {{ post.markdown_text|striptags|truncatechars:100 }}
                {% else %}
                    {{ post.tinymce_text|striptags|truncatechars:100 }}
                {% endif %}
                {% endautoescape %}
            </p>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block content %}
<!-- script src="{% static 'tinymce/js/tinymce/tinymce.min.js' %}"></script>
<script src="{% static 'tinymce/js/textareas.js' %}"></script -->
<script src="{% static 'lib/epiceditor/js/epiceditor.min.js' %}"></script>
<div>
    <div class="post">
        <h2><a href="{% url 'post_markdown' %}" target="_blank">{% if is_new %}新建文章{% else %}编辑文章{% endif %}</a></h2>
        <form id="my_form" method="POST" class="post-form">{% csrf_token %}
            <div class="content">
                <button id="tinymce_btn" type="button" class="save btn btn-default">富文本</button>
                <button id="markdown_btn" type="button" class="save btn btn-default" onclick='location.href="{% url 'post_markdown' %}"' target="_blank" style="margin-right: 5px;">markdown</button>
                <button type="button" class="save btn btn-default" onclick="location.href='/'" style="margin-right: 5px;">取消</button>
                <button id="submit_btn" type="submit" class="save btn btn-default" style="margin-right: 5px;">保存</button>
                <div id="epiceditor">
                    <p>{{ form.as_p }}</p>
                </div>
            </div>
        </form>
    </div>
    <!-- p> I don't know why below form in '<div class="content">' is invaild</p -->
    <div>
        <iframe id="form_target" name="form_target" style="display:none"></iframe>
        <form id="my_form" action="{% url 'blog.views.upload' %}" target="form_target" method="post" enctype="multipart/form-data" style="width:0px;height:0;overflow:hidden">{% csrf_token %}
            <input name="image" type="file" onchange="$('#my_form').submit();this.value='';">
        </form>
    </div>
</div>
<script>
    $("#id_is_markdown").hide();
    $("#id_is_markdown").siblings("label").hide();
    $("#id_markdown_text").hide();
    $("#id_markdown_text").siblings("label").hide();
    $("#id_tinymce_text").hide();
    $("#id_tinymce_text").siblings("label").hide();
    $("#id_text").attr("id","my-edit-area");
    var editor = new EpicEditor({basePath: '/static/lib/epiceditor'}).load();
    $("#submit_btn").click(function(){
        //alert($("#my-edit-area").val());
        //alert(editor.getElement('editor').body.innerHTML);
        //$("#my-edit-area").val(editor.getElement('editor').body.innerHTML);
        $("#id_markdown_text").val(editor.getElement('previewer').body.innerHTML);
    });
    $("#tinymce_btn").click(function(){
        $("#id_is_markdown").attr("checked",false);
        $("#my_form").submit();
    });
    //editor.enterFullscreen(function () {});
</script>
{% endblock %}

blog/templates/blog/post_edit_tinymce.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block content %}
<script src="{% static 'tinymce/js/tinymce/tinymce.min.js' %}"></script>
<script src="{% static 'tinymce/js/textareas.js' %}"></script>
<div>
    <div class="post">
        <h2>{% if is_new %}新建文章{% else %}编辑文章{% endif %}</h2>
        <form id="my_form" method="POST" class="post-form">{% csrf_token %}
            <div class="content">
                <button id="tinymce_btn" type="button" class="save btn btn-default">富文本</button>
                <button id="markdown_btn" type="button" class="save btn btn-default" style="margin-right: 5px;">markdown</button>
                <button type="button" class="save btn btn-default" onclick="location.href='/'" style="margin-right: 5px;">取消</button>
                <button id="submit_btn" type="submit" class="save btn btn-default" style="margin-right: 5px;">保存</button>
                <div id="epiceditor">
                    <p>{{ form.as_p }}</p>
                </div>
            </div>
        </form>
    </div>
    <!-- p> I don't know why below form in '<div class="content">' is invaild</p -->
    <div>
        <iframe id="form_target" name="form_target" style="display:none"></iframe>
        <form id="my_form" action="{% url 'blog.views.upload' %}" target="form_target" method="post" enctype="multipart/form-data" style="width:0px;height:0;overflow:hidden">{% csrf_token %}
            <input name="image" type="file" onchange="$('#my_form').submit();this.value='';">
        </form>
    </div>
</div>
<script>
    $("#id_text").hide();
    $("#id_text").siblings("label").hide();
    $("#id_is_markdown").hide();
    $("#id_is_markdown").siblings("label").hide();
    $("#id_markdown_text").hide();
    $("#id_markdown_text").siblings("label").hide();
    $("#markdown_btn").click(function(){
        $("#id_is_markdown").attr("checked",true);
        $("#my_form").submit();
    });
</script>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block content %}
{% load blog_tags %}
    {% if list_header %}
        <div class="box">{{ list_header }}</div>
    {% endif %}
    {% for post in posts %}
        <div class="post">
            <div>
                <h1><a href="{% url 'blog.views.post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            </div>
            <div class="post_date">
                <p>published: {{ post.published_date }}</p>
            </div>
            <div>
                <p>
                    {% autoescape off %}
                        {% if post.is_markdown %}
                            {{ post.markdown_text|striptags|truncatechars:300 }}
                        {% else %}
                            {{ post.tinymce_text|striptags|truncatechars:300 }}
                        {% endif %}
                    {% endautoescape %}
                </p>
            </div>
        </div>
        <div class="under">
            <span class="categories post_date">category: </span>
            <span>
                <a href="{% url 'blog.views.post_list_by_category' cg=post.category.id %}"
                   rel="category">{{ post.category.name }}
                </a>
            </span>
        </div>
    {% endfor %}
    {% if page %}
        <div class="pagination">
            <span class="step-links">
                {% if posts.has_previous %}
                    <a href="?page={{ posts.previous_page_number }}">previous</a>
                {% endif %}
                <span class="current">
                    Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
                </span>
                {% if posts.has_next %}
                    <a href="?page={{ posts.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% endblock content %}

blog/templates/blog/post_markdown.html
{% load staticfiles %}
<head>
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'lib/epiceditor/js/epiceditor.min.js' %}"></script>
    <title>文斌的博客</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div id="epiceditor" class="col-md-6">
                <textarea id="my-edit-area">
                </textarea>
            </div>
        </div>
    </div>
    <script>
        function heredoc(fn) {
            return fn.toString().split('\n').slice(1,-1).join('\n') + '\n'
        }


        var ttt = heredoc(function(){/*
#Standard Markdown

##Strong and Emphasize
```
*emphasize*   **strong**
_emphasize_   __strong__
```

*emphasize*   **strong**
_emphasize_   __strong__


##Links and Email
[My cnblog](http://juandx.cnblogs.com "juandx")

Reference-style labels (titles are optional):
```
An [example][id]. Then, anywhere
else in the doc, define the link:

  [id]: http://example.com/  "Title"
```
我这里师范怎么好像最后必须有个符号才行。。。

[1]: http://juandx.pythonanywhere.com .


Email:
```
An email <example@example.com> link.
```

Email: <juandx@163.com>

##Images
Inline (titles are optional):
```
![alt text](/path/img.jpg "Title")
```
![陈都灵](http://img01.e23.cn/2015/0423/20150423070516267.jpeg "都灵")

Reference-style:
```
![alt text][id]

[id]: /url/to/img.jpg "Title"
```
##Headers
```
Setext-style:

Header 1
========

Header 2
--------
```
atx-style (closing #’s are optional):
```
# Header 1 #

## Header 2 ##

###### Header 6
```
##Lists
Ordered, without paragraphs:
```
1.  Foo
2.  Bar
```
1. wenbin
2. juandx

Unordered, with paragraphs:
```
*   A list item.

    With multiple paragraphs.

*   Bar
```
You can nest them:
```
*   Abacus
    * answer
*   Bubbles
    1.  bunk
    2.  bupkis
        * BELITTLER
    3. burper
*   Cunning
```
##Blockquotes
```
> Email-style angle brackets
> are used for blockquotes.

> > And, they can be nested.

> #### Headers in blockquotes
>
> * You can quote a list.
> * Etc.
```
##Inline Code
```
`<code>` spans are delimited
by backticks.

You can include literal backticks
like `` `this` ``.
```
##Block Code
Indent every line of a code block by at least 4 spaces or 1 tab.
```
This is a normal paragraph.

    This is a preformatted
    code block.
```
##Horizontal Rules
Three or more dashes or asterisks:
```
---

* * *

- - - -
```
##Hard Line Breaks
End a line with two or more spaces:
```
Roses are red,   
Violets are blue.
```

来自大神的demo:
[http://mahua.jser.me/](http://mahua.jser.me/, "mahua")
     */});
        $("#my-edit-area").val(ttt);
        var editor = new EpicEditor({basePath: '/static/lib/epiceditor'}).load();
        editor.enterFullscreen(function () {
            console.log('Welcome to fullscreen mode!');
        });
    </script>
</body>

blog/templates/blog/post_search_list.html
{% extends 'blog/base.html' %}
{% block content %}
    {% if list_header %}
        <div class="box">{{ list_header }}</div>
    {% endif %}
    {% for post in posts %}
        <div class="post">
            <h2><a href="{% url 'blog.views.post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
        </div>
    {% endfor %}
{% endblock %}